### ISSUE TITLE
This crate is super hard to find on crates.io

### ISSUE THREAD

**Issue by gnzlbg** [bsteinb/accurate#1]
I searched for Kahan, floating point precision, sum, ... and it did not pop up. 

It might be worth it to expend some time doing some crates.io SEO, e.g., expanding the readme with more information, maybe mentioning which algorithms are implemented in this crate, etc.

**Comment by bsteinb** [comment]
I added some more keywords and categories in `Cargo.toml` and added a list of algorithms to `README.md` (though Kahan is not among them).
