### ISSUE TITLE
error[E0034]: multiple applicable items in scope

### ISSUE THREAD

**Issue by ergpopler** [bsteinb/accurate#2]
error[E0034]: multiple applicable items in scope
    --> /home/parrot/.cargo/registry/src/github.com-1ecc6299db9ec823/accurate-0.3.0/src/sum/ifastsum.rs:78:32
     |
78   |                 sm = sm.max(st.abs());
     |                                ^^^ multiple `abs` found
     |
note: candidate #1 is defined in the trait `ieee754::Ieee754`
    --> /home/parrot/.cargo/registry/src/github.com-1ecc6299db9ec823/ieee754-0.2.6/src/traits.rs:472:5
     |
472  |     fn abs(self) -> Self;
     |     ^^^^^^^^^^^^^^^^^^^^^
note: candidate #2 is defined in the trait `num::Float`
    --> /home/parrot/.cargo/registry/src/github.com-1ecc6299db9ec823/num-traits-0.2.12/src/float.rs:1191:5
     |
1191 |     fn abs(self) -> Self;
     |     ^^^^^^^^^^^^^^^^^^^^^
help: disambiguate the associated function for candidate #1
     |
78   |                 sm = sm.max(ieee754::Ieee754::abs(st));
     |                             ^^^^^^^^^^^^^^^^^^^^^^^^^
help: disambiguate the associated function for candidate #2
     |
78   |                 sm = sm.max(num::Float::abs(st));
     |                             ^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0034`.
error: could not compile `accurate`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed

Ubuntu 20.04 
stable-x86_64-unknown-linux-gnu (default)
rustc 1.47.0 (18bf6b4f0 2020-10-07)

**Comment by bsteinb** [comment]
This has been fixed on the master branch for a while, but I never published a new version of the crate. Please run `cargo update` and see if version 0.3.1 fixes the issue.
